"""Tests for app.ingest.adif_importer (§6) — phase 8."""

from datetime import datetime, timezone

from app.core.models import FieldDay, QsoSource, Station
from app.core.status import Status
from app.core.sync_engine import SyncEngine
from app.ingest.adif_importer import (
    adif_qso_id,
    import_adif_file,
    import_adif_text,
    import_adif_to_repository,
)
from app.storage.fieldday_repository import create_fieldday

UTC = timezone.utc
START = datetime(2026, 6, 6, 13, 0, tzinfo=UTC)
END = datetime(2026, 6, 7, 13, 0, tzinfo=UTC)

HEADER = (
    "Generated by N1MM Logger+\n"
    "<ADIF_VER:5>3.1.4\n"
    "<PROGRAMID:4>N1MM\n"
    "<EOH>\n"
)


def make_fieldday(**kwargs) -> FieldDay:
    defaults = dict(id="fd", name="Velddag", start_utc=START, end_utc=END,
                    selected_bands=["160m", "80m", "40m"])
    defaults.update(kwargs)
    return FieldDay(**defaults)


def stations() -> list[Station]:
    return [
        Station(original_callsign="ON4BAF/P", normalized_callsign="ON4BAF"),
        Station(original_callsign="ON4CDZ/P", normalized_callsign="ON4CDZ"),
    ]


def record(call="ON4BAF/P", date="20260606", time="1430", freq="3.52519",
           mode="CW", extra=""):
    return (
        f"<CALL:{len(call)}>{call} <QSO_DATE:8>{date} <TIME_ON:{len(time)}>{time} "
        f"<FREQ:{len(freq)}>{freq} <MODE:{len(mode)}>{mode} "
        f"<STATION_CALLSIGN:7>ON6WL/P <CONTEST_ID:6>FDREG1 {extra}<EOR>\n"
    )


class TestParsing:
    def test_basic_record_with_header(self):
        qsos, report = import_adif_text(
            HEADER + record(), make_fieldday(), stations(), set()
        )
        assert report.records_read == 1
        assert report.imported == 1
        assert len(qsos) == 1
        q = qsos[0]
        assert q.original_callsign == "ON4BAF/P"
        assert q.normalized_callsign == "ON4BAF"
        assert q.frequency_khz == 3525.19          # MHz × 1000 (§6.1)
        assert q.band == "80m"
        assert q.mode == "CW"
        assert q.timestamp_utc == datetime(2026, 6, 6, 14, 30, tzinfo=UTC)
        assert q.source == QsoSource.ADIF
        assert q.source_station == "ON6WL/P"
        assert q.contest_name == "FDREG1"

    def test_no_header_file(self):
        qsos, report = import_adif_text(
            record(), make_fieldday(), stations(), set()
        )
        assert report.imported == 1

    def test_case_insensitive_tags(self):
        text = record().lower().replace("<eor>", "<EOR>")
        qsos, report = import_adif_text(text, make_fieldday(), stations(), set())
        assert report.imported == 1

    def test_time_on_six_digits(self):
        qsos, _ = import_adif_text(
            record(time="143059"), make_fieldday(), stations(), set()
        )
        assert qsos[0].timestamp_utc.second == 59

    def test_band_fallback_when_freq_missing(self):
        text = ("<CALL:8>ON4BAF/P <QSO_DATE:8>20260606 <TIME_ON:4>1430 "
                "<BAND:3>80m <MODE:2>CW <EOR>")
        qsos, report = import_adif_text(text, make_fieldday(), stations(), set())
        assert report.imported == 1
        assert qsos[0].band == "80m"
        assert qsos[0].frequency_khz == 3500.0  # band lower bound placeholder

    def test_type_suffix_in_length(self):
        text = ("<CALL:8:S>ON4BAF/P <QSO_DATE:8:D>20260606 <TIME_ON:4:T>1430 "
                "<FREQ:7:N>3.52519 <MODE:2:S>CW <EOR>")
        _, report = import_adif_text(text, make_fieldday(), stations(), set())
        assert report.imported == 1

    def test_incomplete_last_record_without_eor(self):
        # Complete fields but missing <EOR> at EOF: still processed (§6.1).
        text = record() + ("<CALL:8>ON4CDZ/P <QSO_DATE:8>20260606 "
                           "<TIME_ON:4>1500 <FREQ:7>7.02000 <MODE:2>CW")
        qsos, report = import_adif_text(text, make_fieldday(), stations(), set())
        assert report.records_read == 2
        assert report.imported == 2

    def test_truly_incomplete_last_record(self):
        # Missing timestamp: counted unparseable, no crash.
        text = record() + "<CALL:8>ON4CDZ/P <FREQ:7>7.02000"
        _, report = import_adif_text(text, make_fieldday(), stations(), set())
        assert report.records_read == 2
        assert report.imported == 1
        assert report.unparseable == 1

    def test_operator_fallback_for_source(self):
        text = ("<CALL:8>ON4BAF/P <QSO_DATE:8>20260606 <TIME_ON:4>1430 "
                "<FREQ:7>3.52519 <MODE:2>CW <OPERATOR:5>ON9ZZ <EOR>")
        qsos, _ = import_adif_text(text, make_fieldday(), stations(), set())
        assert qsos[0].source_station == "ON9ZZ"

    def test_comma_decimal_in_freq(self):
        _, report = import_adif_text(
            record(freq="3,52519"), make_fieldday(), stations(), set()
        )
        assert report.imported == 1


class TestClassification:
    def test_unknown_station_ignored_br03(self):
        _, report = import_adif_text(
            record(call="DL1XYZ"), make_fieldday(), stations(), set()
        )
        assert report.unknown_station == 1
        assert report.imported == 0

    def test_outside_period(self):
        _, report = import_adif_text(
            record(date="20260601"), make_fieldday(), stations(), set()
        )
        assert report.outside_period == 1
        assert report.imported == 0

    def test_band_not_selected_stored_and_counted(self):
        qsos, report = import_adif_text(
            record(freq="14.05000"), make_fieldday(), stations(), set()
        )
        assert report.band_not_selected == 1
        assert report.imported == 1          # stored for a later band change
        assert qsos[0].band == "20m"

    def test_no_band_at_all(self):
        _, report = import_adif_text(
            record(freq="5.00000"), make_fieldday(), stations(), set()
        )
        assert report.no_band == 1
        assert report.imported == 0

    def test_strict_mode_respected(self):
        fd = make_fieldday(strict_callsign_matching=True)
        # List has /P; ADIF has bare call → unknown in strict mode.
        _, report = import_adif_text(record(call="ON4BAF"), fd, stations(), set())
        assert report.unknown_station == 1


class TestDedup:
    def test_same_record_twice_in_one_file(self):
        text = record() + record()
        qsos, report = import_adif_text(text, make_fieldday(), stations(), set())
        assert report.records_read == 2
        assert report.imported == 1
        assert report.duplicates == 1

    def test_reimport_same_file_all_duplicates(self):
        fd, st = make_fieldday(), stations()
        first, report1 = import_adif_text(record(), fd, st, set())
        existing = {q.qso_id for q in first}
        _, report2 = import_adif_text(record(), fd, st, existing)
        assert report1.imported == 1
        assert report2.duplicates == 1
        assert report2.imported == 0

    def test_hash_rounds_to_minute(self):
        # Same minute, different seconds → same id (§6.2).
        a = adif_qso_id("ON4BAF", "80m",
                        datetime(2026, 6, 6, 14, 30, 5, tzinfo=UTC), "CW")
        b = adif_qso_id("ON4BAF", "80m",
                        datetime(2026, 6, 6, 14, 30, 55, tzinfo=UTC), "CW")
        c = adif_qso_id("ON4BAF", "80m",
                        datetime(2026, 6, 6, 14, 31, 5, tzinfo=UTC), "CW")
        assert a == b
        assert a != c

    def test_hash_differs_per_band_and_mode(self):
        ts = datetime(2026, 6, 6, 14, 30, tzinfo=UTC)
        assert adif_qso_id("ON4BAF", "80m", ts, "CW") != adif_qso_id(
            "ON4BAF", "40m", ts, "CW"
        )
        assert adif_qso_id("ON4BAF", "80m", ts, "CW") != adif_qso_id(
            "ON4BAF", "80m", ts, "SSB"
        )

    def test_hash_suffix_insensitive(self):
        # /P vs bare call hash identically (loose normalization).
        ts = datetime(2026, 6, 6, 14, 30, tzinfo=UTC)
        text_a = record(call="ON4BAF/P")
        text_b = record(call="ON4BAF")
        fd, st = make_fieldday(), stations()
        qsos_a, _ = import_adif_text(text_a, fd, st, set())
        _, report_b = import_adif_text(text_b, fd, st, {q.qso_id for q in qsos_a})
        assert report_b.duplicates == 1


class TestEngineIntegration:
    def test_adif_marks_matrix(self):
        fd, st = make_fieldday(), stations()
        qsos, _ = import_adif_text(HEADER + record(), fd, st, set())
        engine = SyncEngine(fd, st, qsos, [])
        assert engine.get_cell("ON4BAF", "80m").status == Status.WORKED_BY_N1MM


class TestRepositoryIntegration:
    def test_full_flow(self, tmp_path):
        fd = make_fieldday(id="fd-adif")
        repo = create_fieldday(fd, root_dir=tmp_path)
        repo.save_stations(stations())

        adif_path = tmp_path / "log.adi"
        adif_path.write_text(HEADER + record() + record(call="ON4CDZ/P",
                                                        freq="7.02000"),
                             encoding="utf-8")

        report = import_adif_to_repository(adif_path, repo)
        assert report.imported == 2
        assert report.source_file == "log.adi"
        assert len(repo.load_qsos()) == 2

        # Sync log entry written (§6.3)
        log = repo.load_sync_log()
        assert log[-1]["type"] == "adif_import"
        assert log[-1]["details"]["imported"] == 2

        # Second import: everything duplicate, nothing double-stored.
        report2 = import_adif_to_repository(adif_path, repo)
        assert report2.duplicates == 2
        assert report2.imported == 0
        assert len(repo.load_qsos()) == 2

    def test_unreadable_file_raises(self, tmp_path):
        fd = make_fieldday(id="fd-x")
        repo = create_fieldday(fd, root_dir=tmp_path)
        try:
            import_adif_to_repository(tmp_path / "missing.adi", repo)
        except ValueError as exc:
            assert "Cannot read" in str(exc)
        else:
            raise AssertionError("expected ValueError")
